// constants.ts
export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000/api/';
export const BASEURL = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';
export const SECRET_KEY = process.env.SECRET_KEY || 'JHGJHG&^*&^*&HGJHGJ657668768JHJHGJHG*&^*&^*&^';
export const COMMISSIONPERCENTAGE=18;
const startYear = 1985; // Starting year
const endYear = 2050; 


export const Grades=Array.from({ length: endYear - startYear + 1 }, (_, i) => startYear + i);
export const currencies=[
  { unicode:"$", currency:"USD"},
  // { unicode:"€", currency:"EUR"},
  // { unicode:"£", currency:"GBP"}
];

export const licensePackages=[
  {id:1, minimum_license:1,maximum_license:200, amount:15},
  {id:1, minimum_license:201,maximum_license:500, amount:12},
  {id:1, minimum_license:501,maximum_license:1000, amount:10},
  {id:1, minimum_license:1001,maximum_license:10000, amount:8},
  
];

export const teamlicensePackages=[
  {id:1, minimum_license:1,maximum_license:200, amount:20},
  
  
];



export const turnAroundTime=[
  { id:1, value:"24", label:"24 Hours"},
  { id:2, value:"48", label:"48 Hours"},
  { id:3, value:"72", label:"72 Hours"},
  { id:4, value:"96", label:"96 Hours"},
  { id:5, value:"120", label:"120 Hours"},
  
];
export const countryCodesList = [
    { id: 1, code: "+1", country: "USA" },
    { id: 2, code: "+44", country: "UK" },
    { id: 3, code: "+91", country: "India" },
    { id: 4, code: "+61", country: "Australia" },
    { id: 5, code: "+33", country: "France" },
    { id: 6, code: "+49", country: "Germany" },
    { id: 7, code: "+81", country: "Japan" },
    { id: 8, code: "+55", country: "Brazil" },
    { id: 9, code: "+34", country: "Spain" },
    { id: 10, code: "+39", country: "Italy" },
    { id: 11, code: "+52", country: "Mexico" },
    { id: 12, code: "+7", country: "Russia" },
    { id: 13, code: "+86", country: "China" },
    { id: 14, code: "+27", country: "South Africa" },
    { id: 15, code: "+20", country: "Egypt" },
    { id: 16, code: "+62", country: "Indonesia" },
    { id: 17, code: "+60", country: "Malaysia" },
    { id: 18, code: "+34", country: "Spain" },
    { id: 19, code: "+91", country: "India" },
    { id: 20, code: "+63", country: "Philippines" },
    { id: 21, code: "+90", country: "Turkey" },
    { id: 22, code: "+94", country: "Sri Lanka" },
    { id: 23, code: "+971", country: "UAE" },
    { id: 24, code: "+34", country: "Spain" },
    { id: 25, code: "+27", country: "South Africa" },
    { id: 26, code: "+44", country: "United Kingdom" },
    { id: 27, code: "+55", country: "Brazil" },
    { id: 28, code: "+49", country: "Germany" },
    { id: 29, code: "+62", country: "Indonesia" },
    { id: 30, code: "+52", country: "Mexico" },
    { id: 31, code: "+61", country: "Australia" },
    { id: 32, code: "+33", country: "France" },
    { id: 33, code: "+44", country: "United Kingdom" },
    { id: 34, code: "+1", country: "USA" },
    { id: 35, code: "+968", country: "Oman" },
    { id: 36, code: "+972", country: "Israel" },
    { id: 37, code: "+886", country: "Taiwan" },
    { id: 38, code: "+90", country: "Turkey" },
    { id: 39, code: "+351", country: "Portugal" },
    { id: 40, code: "+977", country: "Nepal" },
    { id: 41, code: "+265", country: "Malawi" },
    { id: 42, code: "+234", country: "Nigeria" },
    { id: 43, code: "+254", country: "Kenya" },
    { id: 44, code: "+1", country: "Canada" },
    { id: 45, code: "+54", country: "Argentina" },
    { id: 46, code: "+48", country: "Poland" },
    { id: 47, code: "+351", country: "Portugal" },
    { id: 48, code: "+20", country: "Egypt" },
    { id: 49, code: "+971", country: "UAE" },
    { id: 50, code: "+962", country: "Jordan" },
    { id: 51, code: "+975", country: "Bhutan" },
    { id: 52, code: "+977", country: "Nepal" },
    { id: 53, code: "+1", country: "USA" },
    { id: 54, code: "+49", country: "Germany" },
    { id: 55, code: "+7", country: "Russia" },
    { id: 56, code: "+60", country: "Malaysia" },
    { id: 57, code: "+92", country: "Pakistan" },
    { id: 58, code: "+370", country: "Lithuania" },
    { id: 59, code: "+502", country: "Guatemala" },
    { id: 60, code: "+504", country: "Honduras" },
    { id: 61, code: "+852", country: "Hong Kong" },
    { id: 62, code: "+63", country: "Philippines" },
    { id: 63, code: "+33", country: "France" },
    { id: 64, code: "+55", country: "Brazil" },
    { id: 65, code: "+56", country: "Chile" },
    { id: 66, code: "+57", country: "Colombia" },
    { id: 67, code: "+60", country: "Malaysia" },
    { id: 68, code: "+503", country: "El Salvador" },
    { id: 69, code: "+91", country: "India" },
    { id: 70, code: "+1", country: "USA" }
  ];

  export const states = [
    { name: "Alabama", abbreviation: "AL" },
    { name: "Alaska", abbreviation: "AK" },
    { name: "Arizona", abbreviation: "AZ" },
    { name: "Arkansas", abbreviation: "AR" },
    { name: "California", abbreviation: "CA" },
    { name: "Colorado", abbreviation: "CO" },
    { name: "Connecticut", abbreviation: "CT" },
    { name: "Delaware", abbreviation: "DE" },
    { name: "Florida", abbreviation: "FL" },
    { name: "Georgia", abbreviation: "GA" },
    { name: "Hawaii", abbreviation: "HI" },
    { name: "Idaho", abbreviation: "ID" },
    { name: "Illinois", abbreviation: "IL" },
    { name: "Indiana", abbreviation: "IN" },
    { name: "Iowa", abbreviation: "IA" },
    { name: "Kansas", abbreviation: "KS" },
    { name: "Kentucky", abbreviation: "KY" },
    { name: "Louisiana", abbreviation: "LA" },
    { name: "Maine", abbreviation: "ME" },
    { name: "Maryland", abbreviation: "MD" },
    { name: "Massachusetts", abbreviation: "MA" },
    { name: "Michigan", abbreviation: "MI" },
    { name: "Minnesota", abbreviation: "MN" },
    { name: "Mississippi", abbreviation: "MS" },
    { name: "Missouri", abbreviation: "MO" },
    { name: "Montana", abbreviation: "MT" },
    { name: "Nebraska", abbreviation: "NE" },
    { name: "Nevada", abbreviation: "NV" },
    { name: "New Hampshire", abbreviation: "NH" },
    { name: "New Jersey", abbreviation: "NJ" },
    { name: "New Mexico", abbreviation: "NM" },
    { name: "New York", abbreviation: "NY" },
    { name: "North Carolina", abbreviation: "NC" },
    { name: "North Dakota", abbreviation: "ND" },
    { name: "Ohio", abbreviation: "OH" },
    { name: "Oklahoma", abbreviation: "OK" },
    { name: "Oregon", abbreviation: "OR" },
    { name: "Pennsylvania", abbreviation: "PA" },
    { name: "Rhode Island", abbreviation: "RI" },
    { name: "South Carolina", abbreviation: "SC" },
    { name: "South Dakota", abbreviation: "SD" },
    { name: "Tennessee", abbreviation: "TN" },
    { name: "Texas", abbreviation: "TX" },
    { name: "Utah", abbreviation: "UT" },
    { name: "Vermont", abbreviation: "VT" },
    { name: "Virginia", abbreviation: "VA" },
    { name: "Washington", abbreviation: "WA" },
    { name: "West Virginia", abbreviation: "WV" },
    { name: "Wisconsin", abbreviation: "WI" },
    { name: "Wyoming", abbreviation: "WY" }
];

export const positionOptionsList = [
  { value: "Goalkeeper", label: "Goalkeeper" },
  { value: "Defender", label: "Defender" },
  { value: "Midfielder", label: "Midfielder" },
  { value: "Center Forward", label: "Center Forward" },
  { value: "Striker", label: "Striker" },
  { value: "Outside Back/ Wingback", label: "Outside Back/ Wingback" },
  { value: "Centerback", label: "Centerback" },
  { value: "Holding Mid", label: "Holding Mid" },
  { value: "Attacking Mid", label: "Attacking Mid" },
  { value: "Winger", label: "Winger" },
  // Add more positions as needed
];

export const positionOptionsList2 = [
  { value: "Goalkeeper", label: "Goalkeeper" },
  { value: "Field Player", label: "Field Player" },
  // Add more positions as needed
];

export const genders=[
  { value:"", label:"Select"},
  { value:"Male", label:"Male"},
  { value:"Female", label:"Female"},
 { value:"Other", label:"Other"}
];

export const playingLevels=[
  { value:"", label:"Select"},
  { value:"Rec", label:"Rec"},
  { value:"Club", label:"Club"},
  { value:"School", label:"School"},
  { value:"Semi Pro", label:"Semi Pro"},
  { value:"Pro", label:"Pro"}
];

export const countries=[
  { label: "United States", value: "US" },
  { label: "Afghanistan", value: "AF" },
  { label: "Albania", value: "AL" },
  { label: "Algeria", value: "DZ" },
  { label: "Andorra", value: "AD" },
  { label: "Angola", value: "AO" },
  { label: "Antigua and Barbuda", value: "AG" },
  { label: "Argentina", value: "AR" },
  { label: "Armenia", value: "AM" },
  { label: "Australia", value: "AU" },
  { label: "Austria", value: "AT" },
  { label: "Azerbaijan", value: "AZ" },
  { label: "Bahamas", value: "BS" },
  { label: "Bahrain", value: "BH" },
  { label: "Bangladesh", value: "BD" },
  { label: "Barbados", value: "BB" },
  { label: "Belarus", value: "BY" },
  { label: "Belgium", value: "BE" },
  { label: "Belize", value: "BZ" },
  { label: "Benin", value: "BJ" },
  { label: "Bhutan", value: "BT" },
  { label: "Bolivia", value: "BO" },
  { label: "Bosnia and Herzegovina", value: "BA" },
  { label: "Botswana", value: "BW" },
  { label: "Brazil", value: "BR" },
  { label: "Brunei Darussalam", value: "BN" },
  { label: "Bulgaria", value: "BG" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Burundi", value: "BI" },
  { label: "Cabo Verde", value: "CV" },
  { label: "Cambodia", value: "KH" },
  { label: "Cameroon", value: "CM" },
  { label: "Canada", value: "CA" },
  { label: "Central African Republic", value: "CF" },
  { label: "Chad", value: "TD" },
  { label: "Chile", value: "CL" },
  { label: "China", value: "CN" },
  { label: "Colombia", value: "CO" },
  { label: "Comoros", value: "KM" },
  { label: "Congo", value: "CG" },
  { label: "Congo, Democratic Republic of the", value: "CD" },
  { label: "Costa Rica", value: "CR" },
  { label: "Croatia", value: "HR" },
  { label: "Cuba", value: "CU" },
  { label: "Cyprus", value: "CY" },
  { label: "Czech Republic", value: "CZ" },
  { label: "Denmark", value: "DK" },
  { label: "Djibouti", value: "DJ" },
  { label: "Dominica", value: "DM" },
  { label: "Dominican Republic", value: "DO" },
  { label: "Ecuador", value: "EC" },
  { label: "Egypt", value: "EG" },
  { label: "El Salvador", value: "SV" },
  { label: "Equatorial Guinea", value: "GQ" },
  { label: "Eritrea", value: "ER" },
  { label: "Estonia", value: "EE" },
  { label: "Eswatini", value: "SZ" },
  { label: "Ethiopia", value: "ET" },
  { label: "Fiji", value: "FJ" },
  { label: "Finland", value: "FI" },
  { label: "France", value: "FR" },
  { label: "Gabon", value: "GA" },
  { label: "Gambia", value: "GM" },
  { label: "Georgia", value: "GE" },
  { label: "Germany", value: "DE" },
  { label: "Ghana", value: "GH" },
  { label: "Greece", value: "GR" },
  { label: "Grenada", value: "GD" },
  { label: "Guatemala", value: "GT" },
  { label: "Guinea", value: "GN" },
  { label: "Guinea-Bissau", value: "GW" },
  { label: "Guyana", value: "GY" },
  { label: "Haiti", value: "HT" },
  { label: "Honduras", value: "HN" },
  { label: "Hungary", value: "HU" },
  { label: "Iceland", value: "IS" },
  { label: "India", value: "IN" },
  { label: "Indonesia", value: "ID" },
  { label: "Iran", value: "IR" },
  { label: "Iraq", value: "IQ" },
  { label: "Ireland", value: "IE" },
  { label: "Israel", value: "IL" },
  { label: "Italy", value: "IT" },
  { label: "Jamaica", value: "JM" },
  { label: "Japan", value: "JP" },
  { label: "Jordan", value: "JO" },
  { label: "Kazakhstan", value: "KZ" },
  { label: "Kenya", value: "KE" },
  { label: "Kiribati", value: "KI" },
  { label: "Korea, Democratic People's Republic of", value: "KP" },
  { label: "Korea, Republic of", value: "KR" },
  { label: "Kuwait", value: "KW" },
  { label: "Kyrgyzstan", value: "KG" },
  { label: "Lao People's Democratic Republic", value: "LA" },
  { label: "Latvia", value: "LV" },
  { label: "Lebanon", value: "LB" },
  { label: "Lesotho", value: "LS" },
  { label: "Liberia", value: "LR" },
  { label: "Libya", value: "LY" },
  { label: "Liechtenstein", value: "LI" },
  { label: "Lithuania", value: "LT" },
  { label: "Luxembourg", value: "LU" },
  { label: "Madagascar", value: "MG" },
  { label: "Malawi", value: "MW" },
  { label: "Malaysia", value: "MY" },
  { label: "Maldives", value: "MV" },
  { label: "Mali", value: "ML" },
  { label: "Malta", value: "MT" },
  { label: "Marshall Islands", value: "MH" },
  { label: "Mauritania", value: "MR" },
  { label: "Mauritius", value: "MU" },
  { label: "Mexico", value: "MX" },
  { label: "Micronesia", value: "FM" },
  { label: "Moldova", value: "MD" },
  { label: "Monaco", value: "MC" },
  { label: "Mongolia", value: "MN" },
  { label: "Montenegro", value: "ME" },
  { label: "Morocco", value: "MA" },
  { label: "Mozambique", value: "MZ" },
  { label: "Myanmar", value: "MM" },
  { label: "Namibia", value: "NA" },
  { label: "Nauru", value: "NR" },
  { label: "Nepal", value: "NP" },
  { label: "Netherlands", value: "NL" },
  { label: "New Zealand", value: "NZ" },
  { label: "Nicaragua", value: "NI" },
  { label: "Niger", value: "NE" },
  { label: "Nigeria", value: "NG" },
  { label: "North Macedonia", value: "MK" },
  { label: "Norway", value: "NO" },
  { label: "Oman", value: "OM" },
  { label: "Pakistan", value: "PK" },
  { label: "Palau", value: "PW" },
  { label: "Palestine", value: "PS" },
  { label: "Panama", value: "PA" },
  { label: "Papua New Guinea", value: "PG" },
  { label: "Paraguay", value: "PY" },
  { label: "Peru", value: "PE" },
  { label: "Philippines", value: "PH" },
  { label: "Poland", value: "PL" },
  { label: "Portugal", value: "PT" },
  { label: "Qatar", value: "QA" },
  { label: "Romania", value: "RO" },
  { label: "Russia", value: "RU" },
  { label: "Rwanda", value: "RW" },
  { label: "Saint Kitts and Nevis", value: "KN" },
  { label: "Saint Lucia", value: "LC" },
  { label: "Saint Vincent and the Grenadines", value: "VC" },
  { label: "Samoa", value: "WS" },
  { label: "San Marino", value: "SM" },
  { label: "Sao Tome and Principe", value: "ST" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Senegal", value: "SN" },
  { label: "Serbia", value: "RS" },
  { label: "Seychelles", value: "SC" },
  { label: "Sierra Leone", value: "SL" },
  { label: "Singapore", value: "SG" },
  { label: "Slovakia", value: "SK" },
  { label: "Slovenia", value: "SI" },
  { label: "Solomon Islands", value: "SB" },
  { label: "Somalia", value: "SO" },
  { label: "South Africa", value: "ZA" },
  { label: "South Sudan", value: "SS" },
  { label: "Spain", value: "ES" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Sudan", value: "SD" },
  { label: "Suriname", value: "SR" },
  { label: "Sweden", value: "SE" },
  { label: "Switzerland", value: "CH" },
  { label: "Syria", value: "SY" },
  { label: "Tajikistan", value: "TJ" },
  { label: "Taiwan", value: "TW" },
  { label: "Tanzania", value: "TZ" },
  { label: "Thailand", value: "TH" },
  { label: "Timor-Leste", value: "TL" },
  { label: "Togo", value: "TG" },
  { label: "Tonga", value: "TO" },
  { label: "Trinidad and Tobago", value: "TT" },
  { label: "Tunisia", value: "TN" },
  { label: "Turkey", value: "TR" },
  { label: "Turkmenistan", value: "TM" },
  { label: "Tuvalu", value: "TV" },
  { label: "Uganda", value: "UG" },
  { label: "Ukraine", value: "UA" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "United Kingdom", value: "GB" },
  
  { label: "Uruguay", value: "UY" },
  { label: "Uzbekistan", value: "UZ" },
  { label: "Vanuatu", value: "VU" },
  { label: "Vatican City", value: "VA" },
  { label: "Venezuela", value: "VE" },
  { label: "Vietnam", value: "VN" },
  { label: "Yemen", value: "YE" },
  { label: "Zambia", value: "ZM" },
  { label: "Zimbabwe", value: "ZW" }
];

